services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py makemigrations &&
                     python manage.py migrate &&
                     python manage.py runserver 0.0.0.0:8000"
